# -*- coding: utf-8 -*-
"""analise_consumo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fPODMuTt9VQZ2r0zruP9VWH69uTpsSRp
"""

hora = 21
consumo_ilum = 0.3
ocupado = False  # escritório vazio

# automação da iluminação
if hora >= 20 and not ocupado and consumo_ilum > 0.2:
    print("Automação: Desligar iluminação -> Economia gerada")

# automação do ar-condicionado
temp_atual = 22
if temp_atual < 23:
    print("Automação: Reduzir ar-condicionado -> Economia adicional")